export const PLAYS = [
  {
    id: 'meta-ads',
    short: 'Meta Ads',
    title: 'Meta Ads',
    kicker: 'Paid social',
    emoji: '📣',
    hook: 'Local businesses burn ad budget on one tired photo. Sell them motion.',
    sell: 'A monthly pack of 8–12 short vertical ad creatives, split into hooks and angles for A/B testing.',
    price: '$800–$2,500/mo retainer, or $150–$400 per creative batch',
    ramp: '3–10 days',
    difficulty: 1,
    build: [
      "Pull the client's existing product photos and storefront shots — you need zero new footage.",
      'Image-to-video each still with a subtle push-in or orbit so the frame breathes instead of sitting static.',
      'Generate 3 distinct opening hooks per angle: problem shot, result shot, pattern-interrupt shot.',
      'Keep every cut under 2s for the first 4 seconds. Export 9:16 and 1:1 from the same generation.',
      'Deliver in a folder named by angle and hook so the client can read the test matrix at a glance.',
    ],
    find: [
      'Businesses already running ads — check the Meta Ad Library for local advertisers with stale static creative.',
      'Med spas, gyms, dentists, roofers, HVAC, auto detailing. High ticket, ad-literate, allergic to filming.',
      'Cold outreach that leads with a free remake of the ad they are currently running.',
    ],
    tip: 'Never sell "videos." Sell creative volume for testing — that is the language performance marketers already think in, and it justifies a recurring fee.',
  },
  {
    id: 'airbnb-walkthroughs',
    short: 'Airbnb',
    title: 'Airbnb Walkthroughs',
    kicker: 'Short-stay hosts',
    emoji: '🛏️',
    hook: 'Every listing has 30 photos and zero video. Turn the photos into the tour.',
    sell: 'A 45–60s walkthrough film built entirely from existing listing photos.',
    price: '$150–$500 per listing',
    ramp: '3–7 days',
    difficulty: 1,
    build: [
      "Take the listing's photo set and order them the way a guest physically moves: entry, living, kitchen, bed, bath, view.",
      'Animate each with a matched camera move so the sequence feels like one continuous walk.',
      'Bridge rooms with a whip-pan or a match cut on a doorway — that transition is what sells the illusion.',
      'End on the exterior or the view pulling out. Add a soft ambient bed, no voiceover needed.',
    ],
    find: [
      'Short-term rental Facebook groups and subreddits — hosts there buy tools constantly.',
      'Property managers with 20+ doors. One contract, twenty listings, same workflow.',
      'Airbnb co-hosts, who get paid on booking rate and will happily expense conversion lifts.',
    ],
    tip: 'Volume is the whole game. Build a repeatable template so listing #12 takes 25 minutes, and price per listing rather than hourly.',
  },
  {
    id: 'real-estate-ads',
    short: 'Real Estate',
    title: 'Real Estate Ads',
    kicker: 'Agents & brokerages',
    emoji: '🔑',
    hook: 'Agents advertise every month and keep posting the same static carousel.',
    sell: 'A monthly creative pack: listing ads, open-house promos, and agent brand spots.',
    price: '$500–$2,000/mo per agent, or $200–$600 per listing campaign',
    ramp: '1–2 weeks',
    difficulty: 1,
    build: [
      'Build the hero from the listing photos — exterior establishing shot drifting up, then the three best interiors.',
      'Generate a golden-hour version of every exterior even if the photos were shot at noon. That one change carries the whole ad.',
      'Cut three hooks per listing: price reveal, the standout feature, and the neighborhood angle.',
      "Put the agent's headshot, name, and number on screen for the last 3 seconds. They will ask for it anyway.",
      'Deliver 9:16 for Reels and Stories plus 1:1 for feed, from the same generation.',
    ],
    find: [
      'Agents running Meta ads already — the Ad Library shows you exactly who, in your zip code, with what.',
      'New listings are the trigger. Watch the MLS feed or Zillow and pitch the day something goes live.',
      'Brokerage marketing directors who buy for the whole office instead of one agent at a time.',
    ],
    tip: 'Disclose virtually staged or enhanced imagery on the ad. Real estate advertising has actual rules, and the disclosure costs you nothing while a complaint can cost the agent their license.',
  },
  {
    id: 'b2b-commercials',
    short: 'B2B Ads',
    title: 'B2B Commercials',
    kicker: 'Companies selling to companies',
    emoji: '🏢',
    hook: 'The highest budgets and the ugliest existing video on the internet.',
    sell: 'Brand films, explainers, and conference loop reels for companies selling to companies.',
    price: '$3,000–$15,000 per project',
    ramp: '3–6 weeks',
    difficulty: 3,
    build: [
      'Abstract the product. B2B software is invisible, so sell the outcome: the calm warehouse, the shipped release.',
      'Generate metaphor footage — flowing networks, precision machinery, cities at speed — instead of screen recordings.',
      'Keep it 60–90s for the site hero, then cut a 15s version for LinkedIn and a silent loop for trade show booths.',
      'Corporate palettes matter. Match their exact brand colors in the grade or it will not get approved.',
    ],
    find: [
      'Series A–C startups that just raised — funding announcements are a buying signal you can read publicly.',
      'Companies with a booth at an upcoming trade show. Deadline plus budget is the ideal client condition.',
      'Marketing agencies who win the account and subcontract the production.',
    ],
    tip: 'B2B buyers are not price-sensitive, they are risk-sensitive. Show a process document and a revision policy and you will out-close cheaper competitors.',
  },
  {
    id: 'website-design',
    short: 'Websites',
    title: 'Website Design',
    kicker: 'Sites & landing pages',
    emoji: '🖥️',
    hook: 'Every template site looks like every other template site. Motion is what makes one look expensive.',
    sell: 'Site builds where the differentiator is custom motion — hero loops, section backgrounds, and product video nobody else has.',
    price: '$2,500–$12,000 per site, plus $300–$800/mo to keep the visuals fresh',
    ramp: '2–5 weeks',
    difficulty: 2,
    build: [
      'Design and build the site first in Framer or Webflow. The video is the finish, not the foundation.',
      'Generate a 6–10s hero loop that cuts seamlessly, then compress it hard — a heavy hero video wrecks your load time and the client will blame the design.',
      'Generate section backgrounds at low contrast on purpose, so headline text stays readable on top of them.',
      'Keep one visual world across the hero, the section beds, and the social preview image. Matching is what reads as designed rather than assembled from stock.',
      'Always ship a static poster frame as the fallback for mobile and slow connections.',
    ],
    find: [
      'Businesses running an obvious off-the-shelf template — you can spot them in about four seconds, and there are thousands per city.',
      'Design studios that lay out beautifully but have no way to produce motion. Subcontract to them instead of competing.',
      'Rebrands, funding announcements, and new locations. A site rebuild is already budgeted at those moments.',
    ],
    tip: 'Line-item the motion separately from the build. "A website" is a commodity people price-shop against Fiverr; "custom motion design" has no comparison price, and it is the part they actually wanted.',
  },
  {
    id: 'yt-shorts',
    short: 'YT Shorts',
    title: 'YT Shorts',
    kicker: 'Faceless channel',
    emoji: '⚡',
    hook: 'A faceless channel that posts three times a day and never runs out of footage.',
    sell: 'Ad revenue, then brand deals, then your own product to the audience you built.',
    price: 'RPM $0.05–$0.30 on Shorts; the real money is the back end',
    ramp: '2–4 months',
    difficulty: 2,
    build: [
      'Pick one visual format and never break it — the algorithm and the viewer both reward recognizability.',
      'Batch: write 30 scripts in one sitting, generate all visuals in a second sitting, edit in a third.',
      'Front-load the strongest visual in frame one. Shorts are won or lost before the first word lands.',
      'Reuse a stock of generated B-roll across videos. A library of 200 clips makes video #100 nearly free.',
    ],
    find: [
      'Not a client business — the platform pays you. Your job is picking a niche advertisers like.',
      'Finance, tech, health, and self-improvement carry the highest RPMs. History and horror carry the lowest.',
    ],
    tip: 'Ten channels at 5 videos each teaches you nothing. One channel at 200 videos teaches you everything. Pick the niche you can stand for a year.',
  },
  {
    id: 'yt-kids',
    short: 'YT Kids',
    title: 'YT Kids',
    kicker: 'Faceless channel',
    emoji: '🧸',
    hook: 'Toddlers rewatch. Rewatch is the only metric that compounds like this.',
    sell: 'Ad revenue on made-for-kids content, plus merch and audio spin-offs.',
    price: 'Lower RPM, enormous watch time; top channels run 7 figures',
    ramp: '4–8 months',
    difficulty: 2,
    build: [
      'Build 2–3 recurring characters and lock their design. Kids follow characters, not topics.',
      'Nursery rhymes, counting, colors, shapes, bedtime. Public-domain songs mean no music licensing.',
      'Generate long-form: stitch 10 segments into a 45-minute compilation. That is the format parents actually put on.',
      'Bright, high-contrast, slow-moving. Frenetic pacing gets flagged and gets skipped.',
    ],
    find: [
      'Platform ad revenue, but note made-for-kids content is non-personalized-ads only — plan RPMs accordingly.',
      'Spin off to Spotify audio, printable activity packs, and plush merch once a character sticks.',
    ],
    tip: 'Read COPPA and the YouTube Kids quality guidelines before you make anything. This niche is lucrative because the compliance bar filters people out.',
  },
]

export const normalizePlayId = (raw) => {
  if (!raw) return null
  const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '')
  const n = norm(raw)
  return PLAYS.find((p) => norm(p.id) === n || norm(p.title) === n)?.id ?? null
}
